#remote_theme: orema10/checkov-theme
remote_theme: carlosperate/jekyll-theme-rtd

site_author: Bridgecrew
repo_url: "https://github.com/bridgecrewio/checkov/"

edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
